// <auto-generated />

using System.Collections.Generic;
using System.Globalization;
using Basin.Config.Interfaces;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Basin
{
    public partial class Basin
    {
        [JsonProperty("Site")] public SiteConfig Site { get; set; }

        [JsonProperty("Driver")] public DriverConfig Driver { get; set; }

        [JsonProperty("Logins")] public List<LoginConfig> Logins { get; set; }
    }

    public class DriverConfig : IDriverConfig
    {
        [JsonProperty("Timeout")] public int Timeout { get; set; }

        [JsonProperty("Browser")] public string Browser { get; set; }
    }

    public class LoginConfig : ILoginConfig
    {
        [JsonProperty("Role")] public string Role { get; set; }

        [JsonProperty("Username")] public string Username { get; set; }

        [JsonProperty("Password")] public string Password { get; set; }

        [JsonProperty("Token")] public string Token { get; set; }
    }

    public class SiteConfig : ISiteConfig
    {
        [JsonProperty("Name")] public string Name { get; set; }

        [JsonProperty("Url")] public string Url { get; set; }
    }

    public partial class Basin
    {
        public static Basin FromJson(string json)
        {
            return JsonConvert.DeserializeObject<Basin>(json, Converter.Settings);
        }
    }

    public static class Serialize
    {
        public static string ToJson(this Basin self)
        {
            return JsonConvert.SerializeObject(self, Converter.Settings);
        }
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter {DateTimeStyles = DateTimeStyles.AssumeUniversal}
            }
        };
    }
}