version: '3'

services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "./selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid/video:/opt/selenoid/video"
      - "./selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-service-startup-timeout", "1m"]
    ports:
      - "4444:4444"
  selenoid-ui:
    network_mode: bridge
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
      - app
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  app:
    network_mode: bridge
    build: ./docker/TheInternet
    ports:
      - "7080:5000"

  chrome:
    image: selenoid/chrome:84.0

  firefox:
    image: selenoid/firefox:79.0
