name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

    steps:
      - uses: actions/checkout@v2
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.300
      - name: Install Dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore
      
      # - name: Publish Nuget
      #   uses: rohith/publish-nuget@v2
      #   with:
      #     PACKAGE_NAME: BasinFramework
      #     PROJECT_FILE_PATH: Basin/Basin.csproj
      #     VERSION_FILE_PATH: Basin/VERSION
      #     VERSION_REGEX: (.*?)
      #     TAG_COMMIT: true
      #     TAG_FORMAT: v*
      #     NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        