name: Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

    steps:
      - uses: actions/checkout@v2
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PACKAGE_NAME: BasinFramework
          PROJECT_FILE_PATH: Basin/Basin.csproj
          VERSION_FILE_PATH: Basin/Basin.csproj
          VERSION_REGEX: <PackageVersion>(.*?)</PackageVersion>
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          body_path: RELEASE_NOTES.md
          
